### ISSUE TITLE
Constantly getting new device notification from Plex

### ISSUE THREAD

**Issue by Resserene** [BenjaminOddou/alfred-plex#6]
Hey,

since I installed the workflow I've been getting "New device accessed your server from Chrome (Chrome)" on my iPhone (through the Plex app) almost everyday at random times. 

I tried deleting the workflow but the notifications still continue. Any idea why this is happening?

**Comment by BenjaminOddou** [comment]
Hey,

This is happening because the server uses the same token that you are using to access your server via chrome. Though receiving notifications should not happen that frequently but maybe you have strict security rules which is fine. I am currently reworking the workflow completely and the connection method will be different. You'll not provide a token but you'll connect to your account which will create a new device in the authorized devices. Plex discover will also change a lot and should resolve your accessibility problem. See you soon for the v2.

**Comment by Resserene** [comment]
> try to remove the device (chrome) from authorized devices

I have nothing with the name Chrome in my authorised devices. That's why it's been hard to get rid of these notifications. 

> ~/Library/Application Support/Alfred/Workflow Data/com.benjamino.plex

I removed this when I deleted the workflow, so not the cause of the issue. 

> ~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.benjamino.plex

I did not find a folder with that name in my Caches folder. 

Any other things I could try to stop the notifications?

> See you soon for the v2

These are great changes. Looking forward to the release.

**Comment by BenjaminOddou** [comment]
@Resserene that's weird indeed. You can also download logs from you server to see in detail what's happening. I have a dedicated button for that in the workflow but you can do it following [this](https://support.plex.tv/articles/200250417-plex-media-server-log-files/).

**Comment by BenjaminOddou** [comment]
@Resserene did you find something ?

**Comment by Resserene** [comment]
I checked the logs but was overwhelmed by the amount of text there. On some scrolling, I did not see anything that could indicate the cause of the problem. I continue to get these random notifications.

**Comment by BenjaminOddou** [comment]
I advise you to change your password + activate otp if not already set. Here is a [Reddit thread](https://reddit.com/r/PleX/s/6XWRczMelv) with someone that has a similar problem. Also if your are using third party plugins for plex, it may triggers notifications.

**Comment by Resserene** [comment]
Will do. Thanks for the help Benjamin 👍
